name: McubeHAS
version: 1.2.8.8
main: de.vmoon.hasplugin.HASPlugin
api-version: '1.21'
authors: [VoidableMoon]
description: A modified Hide and Seek Plugin by VoidableMoon884 and McubeMC
website: https://mcubemc.fr
commands:
  has:
    description: Commande principal.
    permission: has.run
    children:
      has.stop:
        description: Arrête le timer.
        permission: has.stop
      has.version:
        description: Version du plugin.
        permission: has.version
      has.skip:
        description: Skip le timer.
        permission: has.skip
      has.select:
        description: Selectionne le chercheur.
        permission: has.select
        children:
          has.select.random:
            description: Selectionne de manière aléatoire le chercheur.
            permission: has.select.random
      has.teleportall:
        description: Téléporte tous les joueurs aux coordonnnés
        permission: has.teleportall
      has.reload:
        description: Reload la config.
        permission: has.reload
      has.help:
        description: Commande d'aide.
        permission: has.help
      has.beep:
        description: Joue un son.
        permission: has.beep
      has.endgame:
        description: Arrête la partie.
        permission: has.endgame
      has.vote:
        description: Vote de la partie (chercheur)
        permission: has.vote
      has.addtime:
        description: Ajoute du temps
        permission: has.addtime
      has.autor:
        description: Auteur.s du plugin.
        permission: has.autor
      has.debugtime:
        description: Active les commandes de debugs.
        permission: has.debug
      has.language:
        description: Change la langue du plugin [NOT DISPONIBLE POUR MCUBE]
        permission: has.language
  pvp:
    description: Active ou désactive la possibilité de PVP
    permission: pvp.use
    children:
      pvp.on:
        description: Active le PVP
        permission: pvp.on
      pvp.off:
        description: Désactive le PVP
        permission: pvp.off
  hashelp:
    description: Commande d'help
    permission: hashelp.use
    children:
      hashelp.reload:
        description: Help sur le /reload
        permission: hashelp.reload
      hashelp.select:
        description: Help sur le /has select
        permission: hashelp.select
      hashelp.stop:
        description: Help sur le /has stop
        permission: hashelp.stop
      hashelp.teleportall:
        description: Help sur le /has teleportall
        permission: hashelp.teleportall
      hashelp.help:
        description: help sur l'help ?
        permission: hashelp.help
permissions:
  has.run:
    description: Commande de base.
    default: true
  has.stop:
    description: Arrête le timer.
    default: op
  has.select:
    description: Selectionne un chercheur.
    default: op
  has.select.random:
    description: Selectionne un chercheur de manière aléatoire.
    default: op
  has.version:
    description: Affiche la version du plugin.
    default: true
  has.teleportall:
    description: Téléporte tout le monde
    default: op
  has.reload:
    description: Reload.
    default: op
  has.help:
    description: Commande d'aide.
    default: op
  has.skip:
    description: Skip le timer.
    default: op
  has.beep:
    description: Joue un son.
    default: op
  has.endgame:
    description: Arrête la partie
    default: op
  has.vote:
    description: Vote pour la partie(chercheur)
    permission: has.vote
  has.autor:
    description: Auteur.s du plugin
    permission: has.autor
    default: false
  has.addtime:
    description: Ajoute du temps.
    permission: has.addtime
    default: op
  has.debug:
    description: Commande de debug
    permission: has.debug
    default: false
  has.language:
    description: Change la langue du plugin [NOT DISPONIBLE POUR MCUBE]
    permission: has.language
  pvp.use:
    description: Active ou désactive le PVP
    default: op
  pvp.on:
    description: Active le PVP
    default: op
  pvp.off:
    description: Désactive le PVP
    default: op
  hashelp.use:
    description: Help sur le /has
    default: op
  hashelp.reload:
    description: Help sur le /has reload
    default: op
  hashelp.select:
    description: Help sur le /has select
    default: op
  hashelp.stop:
    description: Help sur le /has stop
    default: op
  hashelp.teleportall:
    description: Help sur le /has teleportall
    default: op
  hashelp.help:
    description: Help sur le Hilfe.
    default: op